CommandLog:
  Enabled: true
  DisableMentions: true
  IntervalInSeconds: 5
  Format:
    - '**$username$** [`$timezone$ $time$`] ($UUID$) issued:'
    - '> $message$'
  TimeZone: UTC
  ChannelID: '000000000000000000'
