CommandLogger:
  Enabled: true
  ChannelID: '000000000000000000'
  IntervalInSeconds: 5
  Format:
    - '**%username_escape_markdown%** [`%timezone% %time%`] (%UUID%) issued:'
    - '> %message_escape_markdown%'
  TimeZone: UTC
Link:
  Enabled: true
  ChannelID: '000000000000000000'
Unlink:
  Enabled: true
  ChannelID: '000000000000000000'
